###  Packages 

- Packages are a way of structuring many packages and modules which helps in a well-organized hierarchy of data set, 
- making the directories and modules easy to access. 
- Just like there are different drives and folders in an OS to help us store files,
- similarly packages help us in storing other sub-packages and modules, so that it can be used by the user when necessary

- Pros:
    - Structured Code
    - Easy LookUp
    - Modularity

### Creating

To tell Python that a particular directory is a package, 
 
 - we create a file named __init__.py inside it and then it is considered as a package and we may create other modules and sub-packages within it. 

- This __init__.py file can be left blank or can be coded with the initialization code for the package.

In [ ]:
__init__.py

### To create a package in Python, we need to follow these three simple steps:

1. First, we create a directory and give it a package name, preferably related to its operation.
2. Then we put the classes and the required functions in it.

3. Finally we create an __init__.py file inside the directory, to let Python know that the directory is a package.

### Importing the Packages

- In python to import any packages we use import keyword

- syntax:
    import package-name
### Different Way of importing

In [ ]:
# os sys requests hashlib random array

In [1]:
import os #

os.getcwd()

'D:\\SaiMedha\\Python Essentials\\clsNotebooks\\Functions-Module-Packages'

In [2]:
os.listdir()

['.ipynb_checkpoints',
 'Build-In_Modules.ipynb',
 'Coding Question.ipynb',
 'Collections & Itertools.ipynb',
 'Modules Installation And Environment.ipynb',
 'Packages .ipynb',
 'Python Functions .ipynb']

In [ ]:
os.chdir("../")
print(os.getcwd())
os.listdir()

In [ ]:
os.getcwd()

In [ ]:
os.listdir()
os.getcwd()
os.chdir()
os.mkdir()
os.rmdir()


In [3]:
os.mkdir("Python-JanSession")
os.listdir()


['.ipynb_checkpoints',
 'Build-In_Modules.ipynb',
 'Coding Question.ipynb',
 'Collections & Itertools.ipynb',
 'Modules Installation And Environment.ipynb',
 'Packages .ipynb',
 'Python Functions .ipynb',
 'Python-JanSession']

In [ ]:
os.getcwd()

In [4]:
os.rmdir("Python-JanSession")

In [ ]:
import os
os.getcwd()

In [ ]:
os.chdir("D:\\JS\\Python_Oct_2K22\\ClassFiles\\Functions & Modules & Packages\\Package")
os.listdir()

In [ ]:
import BannkApp

In [ ]:
dir(BannkApp)

In [ ]:
import BannkApp.BankUtil as bank

In [ ]:
bank.addAmount(1000)

In [ ]:
Calculator.welcome.getDir()

In [ ]:
import Calculator.welcome as w

In [ ]:
dir(w)

In [ ]:
w.getDir()

In [ ]:
w.getInfo()

In [ ]:
w.greet("Ganesh")

In [ ]:
from Calculator import evenodd

In [ ]:
evenodd.even(11)

In [ ]:
evenodd.odd(13)

In [ ]:
import Calculator.calcimethods as calci

In [ ]:
dir(calci)

In [ ]:
calci.add()v

In [ ]:
#  create a package with a name Student
#  create a module with name stuFunctions
# create a module with stuJobs
#  create a module with generalAssignm

In [6]:
#1. way of import 
import math

print(dir(math))


['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [7]:
math.sqrt(10)

3.1622776601683795

In [8]:
math.factorial(3)

6

In [9]:
math.gcd(10,20)

10

In [11]:
math.cos(10)

-0.8390715290764524

In [13]:
math.sin(90)

0.8939966636005579

In [ ]:
#2-way of import 

In [15]:
import math as m
m.sqrt(9)
m.log(100)

4.605170185988092

In [16]:
import numpy as np

arr = np.array([[1,2,3],[10,20,30],[40,50,50]])
print(arr)

[[ 1  2  3]
 [10 20 30]
 [40 50 50]]


In [17]:
#3 - way of importing
from pandas import DataFrame

In [19]:
# pd = DataFrame()

In [20]:
from math import gcd,factorial,sin

In [24]:
gcd(10,20)
factorial(6)
sin(67)

-0.8555199789753223

In [36]:
## 4 - way 

from time import *

localtime()

time.struct_time(tm_year=2023, tm_mon=1, tm_mday=29, tm_hour=13, tm_min=16, tm_sec=4, tm_wday=6, tm_yday=29, tm_isdst=0)

In [ ]:
# 1. Traditional or Basic import 

import math

# math.pi
# math.gcd()

# 2. if the package name of module is too long , we can use alias using the as keyword 

import math as mt

# 3 Import a Particular Function from a Package or Sub Module

from math import pi

# 4 Importing all the methods & sub modules in the packages

from math import *
# gcd()



In [ ]:
dir(math)

In [ ]:
import math
print(math.factorial(6))
math.gcd(20 , 2)

In [ ]:
math.sin(90)

In [ ]:
math.pi #attribute

In [ ]:
math.floor(4.3)


In [ ]:
math.ceil(4.3)

In [ ]:
math.pow(2,3)

In [ ]:
math.sqrt(100)

In [ ]:
#importing 2 

import math as m

In [ ]:
m.factorial(3)

In [ ]:
m.pow(2,3)

In [ ]:
from math import pi,gcd
pi

In [ ]:
gcd(5,10)

In [ ]:
# 3 importing 
from math import pi , gcd , factorial

In [ ]:
gcd(10,30)

In [ ]:
# 4 importing
from math import * # importing all functions

In [ ]:
gcd(10,40)

In [ ]:
factorial(10)

In [ ]:
from BannkApp.BankUtil import addAmount,takeLoan

In [ ]:
addAmount(100)

In [ ]:
takeLoan(100)